services:
  postgres-customer:
    container_name: postgres-customer
    image: postgres
    environment:
      POSTGRES_USER: fcastro
      POSTGRES_PASSWORD: password
      PGDATA: /data/postgres
    volumes:
      - postgres-customer:/data/postgres
    ports:
      - "5432:5432"
    networks:
      - postgres
      - spring
    restart: always
  postgres-fraud:
    container_name: postgres-fraud
    image: postgres
    environment:
      POSTGRES_USER: fcastro
      POSTGRES_PASSWORD: password
      PGDATA: /data/postgres
    volumes:
      - postgres-fraud:/data/postgres
    ports:
      - "5433:5432"
    networks:
      - postgres
      - spring
    restart: always
  postgres-notification:
    container_name: postgres-notification
    image: postgres
    environment:
      POSTGRES_USER: fcastro
      POSTGRES_PASSWORD: password
      PGDATA: /data/postgres
    volumes:
      - postgres-notification:/data/postgres
    ports:
      - "5434:5432"
    networks:
      - postgres
      - spring
    restart: always
  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-pgadmin4@pgadmin.org}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-admin}
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    volumes:
      - pgadmin:/var/lib/pgadmin
    ports:
      - "5050:80"
    networks:
      - postgres
    restart: unless-stopped
  rabbitmq:
    image: rabbitmq:3.9.11-management-alpine
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - spring
  zipkin:
    image: openzipkin/zipkin
    container_name: zipkin
    ports:
      - "9411:9411"
    networks:
      - spring
#   eureka-server:
#     image: fernandacastro/eureka-server:latest
#     container_name: eureka-server
#     ports:
#       - "8761:8761"
#     environment:
#       - SPRING_PROFILES_ACTIVE=docker
#     networks:
#       - spring
#     depends_on:
#       - zipkin
#   api-gateway:
#     image: fernandacastro/api-gateway:latest
#     container_name: api-gateway
#     ports:
#       - "8083:8083"
#     environment:
#       - SPRING_PROFILES_ACTIVE=docker
#     networks:
#       - spring
#     depends_on:
#       - zipkin
#       - eureka-server
  customer:
    image: fernandacastro/customer:latest
    container_name: customer
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    networks:
      - postgres
      - spring
    depends_on:
      - postgres-customer
      - zipkin
      - rabbitmq
  fraud:
    image: fernandacastro/fraud:latest
    container_name: fraud
    ports:
      - "8081:8081"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    networks:
      - postgres
      - spring
    depends_on:
      - postgres-fraud
      - zipkin
  notification:
    image: fernandacastro/notification:latest
    container_name: notification
    ports:
      - "8082:8082"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    networks:
      - postgres
      - spring
    depends_on:
      - postgres-notification
      - zipkin
      - rabbitmq
networks:
  postgres:
    driver: bridge
  spring:
    driver: bridge

volumes:
  postgres-customer:
  postgres-fraud:
  postgres-notification:
  pgadmin:

## Run from the Terminal
#docker compose up -d
#networks is postgres so both containers(postgres and pgadmin) can talk to each other by the same network
#RabbitMQ Management guest/guest
#mvn clean package -P build-docker-image (Package and push the image to DockerHub)